apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  labels:
    app: {{ .Values.appName}}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          
